name: zyduspod
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  archive: ^4.0.7
  mobile_scanner: ^7.0.1
  image_picker: ^1.0.7
  image: ^4.1.7
  http_parser: ^4.0.2
  shared_preferences: ^2.5.3
  mlkit_document_scanner: ^0.0.10
  flutter_pdfview: ^1.4.1+1
  # pdf_render: ^1.4.12   # REMOVE this line (legacy V1 embedding causes build failure)
  open_filex: ^4.5.0
  pdf: ^3.10.8
  http: ^1.2.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  path: ^1.9.0
  flutter_doc_scanner: ^0.0.8

  # Use these for PDF -> image rasterization and QR decoding
  printing: ^5.13.0
  zxing2: ^0.2.4 # upgrade from 0.2.4 so QRCodeReader is available
  file_picker: ^10.3.3
  flutter_bloc: ^9.1.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/branding/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/branding/logo.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/branding/logo.png
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/branding/logo.png
  android_12:
    image: assets/branding/logo.png
    icon_background_color: "#FFFFFF"
